---
- hosts: localhost
  vars:
    vault_keys_list: []
    vault_addr: "https://vault.service.consul"

  tasks:
  - include_vars: secrets.yml

#  - name: Set facts
#    include: set_facts.yml
#    tags:
#      - set_facts

  - name: Add pipelines vars
    include: add_vars.yml
    with_dict: "{{ pipelines }}"

  - name: TEMP add global github creds
    uri:
     url: "{{ vault_addr }}:8200/v1/concourse/main/{{ github_login }}"
     method: POST
     headers:
      X-Vault-Token: "{{ vault_token }}"
     body: '{ "value": {{ github_password | to_json }} }'
     validate_certs: no
     status_code: 204

  # - copy: content={{ git_ssh_key }} dest=../concourse/ssh_key
  # - shell: vault kv put /concourse/main/test-pipeline/ssh_key value=@../concourse/ssh_key
  #   environment:
  #     VAULT_TOKEN: "{{ vault_token }}"
