---
jobs:

- name: build-tools
  serial: true
  plan:
  - get: master 
  - put: docker-image
    params: {build: master}

- name: compile-spa
  serial: true
  plan:
  - get: master
    trigger: true
  - task: build-application
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: node 
          #repository: registry-443.service.consul/linux/app 
          #username: ((docker_login)) 
          #password: ((docker_password))
          #ca_certs: 
          #- domain: registry-443.service.consul 
          #  cert: ((ca_cert))        
      inputs:
      - name: master 
      outputs:
      - name: public 
      params:
        CONTENTFUL_ACCESS_TOKEN: ((contentful_api))
        CONTENTFUL_SPACE_ID: ((contentful_id))
        GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: "true"
      caches:
        - path: master/.cache
        - path: master/node_modules
      run:
        path: /bin/sh
        args:
          - -c
          - |
              cd master
              export PATH=$PWD/node_modules/.bin:$PATH
              npm install gatsby@2.25.4
              npm install
              #./node_modules/.bin/gatsby build --log-pages
              gatsby build --log-pages
              cp Dockerhub_Dockerfile ../public/Dockerfile
  - put: dockerhub-push
    params: 
      build: public 
      tag_file: master/.git/ref
      tag_prefix: dev-

resources:

- name: master
  type: git
  source:
    uri: https://github.com/ed201971/contentful.git
    branch: master

- name: docker-image
  type: docker-image
  source:
    username: ((docker_login)) 
    password: ((docker_password))
    repository: registry-443.service.consul/linux/app
    ca_certs: 
    - domain: registry-443.service.consul 
      cert: ((ca_cert))
- name: dockerhub-push
  type: docker-image
  source:
    repository: ed201971/cful
    username: ((dockerhub_login))
    password: ((dockerhub_password))
