[build]
  publish = "public/"
  #command = "gatsby build"
  command = "cross-env GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
